MERGE INTO Common.Country as trgt
USING (
	VALUES
(1,  N'AFG', N'Afghanistan',                                 1, N'AF', N'004'),
(2,  N'ALA', N'Åland Islands',                               1, N'AX', N'248'),
(3,  N'ALB', N'Albania',                                     1, N'AL', N'008'),
(4,  N'DZA', N'Algeria',                                     1, N'DZ', N'012'),
(5,  N'ASM', N'American Samoa',                              1, N'AS', N'016'),
(6,  N'AND', N'Andorra',                                     1, N'AD', N'020'),
(7,  N'AGO', N'Angola',                                      0, N'AO', N'024'),
(8,  N'AIA', N'Anguilla',                                    0, N'AI', N'660'),
(9,  N'ATA', N'Antarctica',                                  0, N'AQ', N'010'),
(10, N'ATG', N'Antigua and Barbuda',                         0, N'AG', N'028'),
(11, N'ARG', N'Argentina',                                   0, N'AR', N'032'),
(12, N'ARM', N'Armenia',                                     0, N'AM', N'051'),
(13, N'ABW', N'Aruba',                                       0, N'AW', N'533'),
(14, N'AUS', N'Australia',                                   0, N'AU', N'036'),
(15, N'AUT', N'Austria',                                     0, N'AT', N'040'),
(16, N'AZE', N'Azerbaijan',                                  0, N'AZ', N'031'),
(17, N'BHS', N'Bahamas',                                     0, N'BS', N'044'),
(18, N'BHR', N'Bahrain',                                     0, N'BH', N'048'),
(19, N'BGD', N'Bangladesh',                                  0, N'BD', N'050'),
(20, N'BRB', N'Barbados',                                    0, N'BB', N'052'),
(21, N'BLR', N'Belarus',                                     0, N'BY', N'112'),
(22, N'BEL', N'Belgium',                                     0, N'BE', N'056'),
(23, N'BLZ', N'Belize',                                      0, N'BZ', N'084'),
(24, N'BEN', N'Benin',                                       0, N'BJ', N'204'),
(25, N'BMU', N'Bermuda',                                     0, N'BM', N'060'),
(26, N'BTN', N'Bhutan',                                      0, N'BT', N'064'),
(27, N'BOL', N'Bolivia (Plurinational State of)',            0, N'BO', N'068'),
(28, N'BES', N'Bonaire, Sint Eustatius and Saba',            0, N'BQ', N'535'),
(29, N'BIH', N'Bosnia and Herzegovina',                      0, N'BA', N'070'),
(30, N'BWA', N'Botswana',                                    0, N'BW', N'072'),
(31, N'BVT', N'Bouvet Island',                               0, N'BV', N'074'),
(32, N'BRA', N'Brazil',                                      0, N'BR', N'076'),
(33, N'IOT', N'British Indian Ocean Territory',              0, N'IO', N'086'),
(34, N'BRN', N'Brunei Darussalam',                           0, N'BN', N'096'),
(35, N'BGR', N'Bulgaria',                                    0, N'BG', N'100'),
(36, N'BFA', N'Burkina Faso',                                0, N'BF', N'854'),
(37, N'BDI', N'Burundi',                                     0, N'BI', N'108'),
(38, N'CPV', N'Cabo Verde',                                  0, N'CV', N'132'),
(39, N'KHM', N'Cambodia',                                    0, N'KH', N'116'),
(40, N'CMR', N'Cameroon',                                    0, N'CM', N'120'),
(41, N'CAN', N'Canada',                                      0, N'CA', N'124'),
(42, N'CYM', N'Cayman Islands',                              0, N'KY', N'136'),
(43, N'CAF', N'Central African Republic',                    0, N'CF', N'140'),
(44, N'TCD', N'Chad',                                        0, N'TD', N'148'),
(45, N'CHL', N'Chile',                                       0, N'CL', N'152'),
(46, N'CHN', N'China',                                       0, N'CN', N'156'),
(47, N'CXR', N'Christmas Island',                            0, N'CX', N'162'),
(48, N'CCK', N'Cocos (Keeling) Islands',                     0, N'CC', N'166'),
(49, N'COL', N'Colombia',                                    0, N'CO', N'170'),
(50, N'COM', N'Comoros',                                     0, N'KM', N'174'),
(51, N'COG', N'Congo',                                       0, N'CD', N'180'),
(52, N'COD', N'Congo, Democratic Republic of the',           0, N'CG', N'178'),
(53, N'COK', N'Cook Islands',                                0, N'CK', N'184'),
(54, N'CRI', N'Costa Rica',                                  0, N'CR', N'188'),
(55, N'CIV', N'Côte d''Ivoire',                              0, N'CI', N'384'),
(56, N'HRV', N'Croatia',                                     0, N'HR', N'191'),
(57, N'CUB', N'Cuba',                                        0, N'CU', N'192'),
(58, N'CUW', N'Curaçao',                                     0, N'CW', N'531'),
(59, N'CYP', N'Cyprus',                                      0, N'CY', N'196'),
(60, N'CZE', N'Czechia',                                     0, N'CZ', N'203'),
(61, N'DNK', N'Denmark',                                     0, N'DK', N'208'),
(62, N'DJI', N'Djibouti',                                    0, N'DJ', N'262'),
(63, N'DMA', N'Dominica',                                    0, N'DM', N'212'),
(64, N'DOM', N'Dominican Republic',                          0, N'DO', N'214'),
(65, N'ECU', N'Ecuador',                                     0, N'EC', N'218'),
(66, N'EGY', N'Egypt',                                       0, N'EG', N'818'),
(67, N'SLV', N'El Salvador',                                 0, N'SV', N'222'),
(68, N'GNQ', N'Equatorial Guinea',                           0, N'GQ', N'226'),
(69, N'ERI', N'Eritrea',                                     0, N'ER', N'232'),
(70, N'EST', N'Estonia',                                     0, N'EE', N'233'),
(71, N'SWZ', N'Eswatini',                                    0, N'SZ', N'748'),
(72, N'ETH', N'Ethiopia',                                    0, N'ET', N'231'),
(73, N'FLK', N'Falkland Islands (Malvinas)',                 0, N'FK', N'238'),
(74, N'FRO', N'Faroe Islands',                               0, N'FO', N'234'),
(75, N'FJI', N'Fiji',                                        0, N'FJ', N'242'),
(76, N'FIN', N'Finland',                                     0, N'FI', N'246'),
(77, N'FRA', N'France',                                      0, N'FR', N'250'),
(78, N'GUF', N'French Guiana',                               0, N'GF', N'254'),
(79, N'PYF', N'French Polynesia',                            0, N'PF', N'258'),
(80, N'ATF', N'French Southern Territories',                 0, N'TF', N'260'),
(81, N'GAB', N'Gabon',                                       0, N'GA', N'266'),
(82, N'GMB', N'Gambia',                                      0, N'GM', N'270'),
(83, N'GEO', N'Georgia',                                     0, N'GE', N'268'),
(84, N'DEU', N'Germany',                                     0, N'DE', N'276'),
(85, N'GHA', N'Ghana',                                       0, N'GH', N'288'),
(86, N'GIB', N'Gibraltar',                                   0, N'GI', N'292'),
(87, N'GRC', N'Greece',                                      0, N'GR', N'300'),
(88, N'GRL', N'Greenland',                                   0, N'GL', N'304'),
(89, N'GRD', N'Grenada',                                     0, N'GD', N'308'),
(90, N'GLP', N'Guadeloupe',                                  0, N'GP', N'312'),
(91, N'GUM', N'Guam',                                        0, N'GU', N'316'),
(92, N'GTM', N'Guatemala',                                   0, N'GT', N'320'),
(93, N'GGY', N'Guernsey',                                    0, N'GG', N'831'),
(94, N'GIN', N'Guinea',                                      0, N'GN', N'324'),
(95, N'GNB', N'Guinea-Bissau',                               0, N'GW', N'624'),
(96, N'GUY', N'Guyana',                                      0, N'GY', N'328'),
(97, N'HTI', N'Haiti',                                       0, N'HT', N'332'),
(98, N'HMD', N'Heard Island and McDonald Islands',           0, N'HM', N'334'),
(99, N'VAT', N'Holy See',                                    0, N'VA', N'336'),
(100,N'HND', N'Honduras',                                    0, N'HN', N'340'),
(101,N'HKG', N'Hong Kong',                                   0, N'HK', N'344'),
(102,N'HUN', N'Hungary',                                     0, N'HU', N'348'),
(103,N'ISL', N'Iceland',                                     0, N'IS', N'352'),
(104,N'IND', N'India',                                       0, N'IN', N'356'),
(105,N'IDN', N'Indonesia',                                   0, N'ID', N'360'),
(106,N'IRN', N'Iran (Islamic Republic of)',                  0, N'IR', N'364'),
(107,N'IRQ', N'Iraq',                                        0, N'IQ', N'368'),
(108,N'IRL', N'Ireland',                                     1, N'IE', N'372'),
(109,N'IMN', N'Isle of Man',                                 0, N'IM', N'833'),
(110,N'ISR', N'Israel',                                      0, N'IL', N'376'),
(111,N'ITA', N'Italy',                                       0, N'IT', N'380'),
(112,N'JAM', N'Jamaica',                                     0, N'JM', N'388'),
(113,N'JPN', N'Japan',                                       0, N'JP', N'392'),
(114,N'JEY', N'Jersey',                                      0, N'JE', N'832'),
(115,N'JOR', N'Jordan',                                      0, N'JO', N'400'),
(116,N'KAZ', N'Kazakhstan',                                  0, N'KZ', N'398'),
(117,N'KEN', N'Kenya',                                       0, N'KE', N'404'),
(118,N'KIR', N'Kiribati',                                    0, N'KI', N'296'),
(119,N'PRK', N'Korea (Democratic People''s Republic of)',    0, N'KP', N'408'),
(120,N'KOR', N'Korea, Republic of',                          0, N'KR', N'410'),
(121,N'KWT', N'Kuwait',                                      0, N'KW', N'414'),
(122,N'KGZ', N'Kyrgyzstan',                                  0, N'KG', N'417'),
(123,N'LAO', N'Lao People''s Democratic Republic',           0, N'LA', N'418'),
(124,N'LVA', N'Latvia',                                      0, N'LV', N'428'),
(125,N'LBN', N'Lebanon',                                     0, N'LB', N'422'),
(126,N'LSO', N'Lesotho',                                     0, N'LS', N'426'),
(127,N'LBR', N'Liberia',                                     0, N'LR', N'430'),
(128,N'LBY', N'Libya',                                       0, N'LY', N'434'),
(129,N'LIE', N'Liechtenstein',                               0, N'LI', N'438'),
(130,N'LTU', N'Lithuania',                                   0, N'LT', N'440'),
(131,N'LUX', N'Luxembourg',                                  0, N'LU', N'442'),
(132,N'MAC', N'Macao',                                       0, N'MO', N'446'),
(133,N'MDG', N'Madagascar',                                  0, N'MG', N'450'),
(134,N'MWI', N'Malawi',                                      0, N'MW', N'454'),
(135,N'MYS', N'Malaysia',                                    0, N'MY', N'458'),
(136,N'MDV', N'Maldives',                                    0, N'MV', N'462'),
(137,N'MLI', N'Mali',                                        0, N'ML', N'466'),
(138,N'MLT', N'Malta',                                       0, N'MT', N'470'),
(139,N'MHL', N'Marshall Islands',                            0, N'MH', N'584'),
(140,N'MTQ', N'Martinique',                                  0, N'MQ', N'474'),
(141,N'MRT', N'Mauritania',                                  0, N'MR', N'478'),
(142,N'MUS', N'Mauritius',                                   0, N'MU', N'480'),
(143,N'MYT', N'Mayotte',                                     0, N'YT', N'175'),
(144,N'MEX', N'Mexico',                                      0, N'MX', N'484'),
(145,N'FSM', N'Micronesia (Federated States of)',            0, N'FM', N'583'),
(146,N'MDA', N'Moldova, Republic of',                        0, N'MD', N'498'),
(147,N'MCO', N'Monaco',                                      0, N'MC', N'492'),
(148,N'MNG', N'Mongolia',                                    0, N'MN', N'496'),
(149,N'MNE', N'Montenegro',                                  0, N'ME', N'499'),
(150,N'MSR', N'Montserrat',                                  0, N'MS', N'500'),
(151,N'MAR', N'Morocco',                                     0, N'MA', N'504'),
(152,N'MOZ', N'Mozambique',                                  0, N'MZ', N'508'),
(153,N'MMR', N'Myanmar',                                     0, N'MM', N'104'),
(154,N'NAM', N'Namibia',                                     0, N'NA', N'516'),
(155,N'NRU', N'Nauru',                                       0, N'NR', N'520'),
(156,N'NPL', N'Nepal',                                       0, N'NP', N'524'),
(157,N'NLD', N'Netherlands',                                 0, N'NL', N'528'),
(158,N'NCL', N'New Caledonia',                               0, N'NC', N'540'),
(159,N'NZL', N'New Zealand',                                 0, N'NZ', N'554'),
(160,N'NIC', N'Nicaragua',                                   0, N'NI', N'558'),
(161,N'NER', N'Niger',                                       0, N'NE', N'562'),
(162,N'NGA', N'Nigeria',                                     0, N'NG', N'566'),
(163,N'NIU', N'Niue',                                        0, N'NU', N'570'),
(164,N'NFK', N'Norfolk Island',                              0, N'NF', N'574'),
(165,N'MKD', N'North Macedonia',                             0, N'MK', N'807'),
(166,N'MNP', N'Northern Mariana Islands',                    0, N'MP', N'580'),
(167,N'NOR', N'Norway',                                      0, N'NO', N'578'),
(168,N'OMN', N'Oman',                                        0, N'OM', N'512'),
(169,N'PAK', N'Pakistan',                                    0, N'PK', N'586'),
(170,N'PLW', N'Palau',                                       0, N'PW', N'585'),
(171,N'PSE', N'Palestine, State of',                         0, N'PS', N'275'),
(172,N'PAN', N'Panama',                                      0, N'PA', N'591'),
(173,N'PNG', N'Papua New Guinea',                            0, N'PG', N'598'),
(174,N'PRY', N'Paraguay',                                    0, N'PY', N'600'),
(175,N'PER', N'Peru',                                        0, N'PE', N'604'),
(176,N'PHL', N'Philippines',                                 0, N'PH', N'608'),
(177,N'PCN', N'Pitcairn',                                    0, N'PN', N'612'),
(178,N'POL', N'Poland',                                      0, N'PL', N'616'),
(179,N'PRT', N'Portugal',                                    0, N'PT', N'620'),
(180,N'PRI', N'Puerto Rico',                                 0, N'PR', N'630'),
(181,N'QAT', N'Qatar',                                       0, N'QA', N'634'),
(182,N'REU', N'Réunion',                                     0, N'RE', N'638'),
(183,N'ROU', N'Romania',                                     0, N'RO', N'642'),
(184,N'RUS', N'Russian Federation',                          0, N'RU', N'643'),
(185,N'RWA', N'Rwanda',                                      0, N'RW', N'646'),
(186,N'BLM', N'Saint Barthélemy',                            0, N'BL', N'652'),
(187,N'SHN', N'Saint Helena, Ascension and Tristan da Cunha',0, N'SH', N'654'),
(188,N'KNA', N'Saint Kitts and Nevis',                       0, N'KN', N'659'),
(189,N'LCA', N'Saint Lucia',                                 0, N'LC', N'662'),
(190,N'MAF', N'Saint Martin (French part)',                  0, N'MF', N'663'),
(191,N'SPM', N'Saint Pierre and Miquelon',                   0, N'PM', N'666'),
(192,N'VCT', N'Saint Vincent and the Grenadines',            0, N'VC', N'670'),
(193,N'WSM', N'Samoa',                                       0, N'WS', N'882'),
(194,N'SMR', N'San Marino',                                  0, N'SM', N'674'),
(195,N'STP', N'Sao Tome and Principe',                       0, N'ST', N'678'),
(196,N'SAU', N'Saudi Arabia',                                0, N'SA', N'682'),
(197,N'SEN', N'Senegal',                                     0, N'SN', N'686'),
(198,N'SRB', N'Serbia',                                      0, N'RS', N'688'),
(199,N'SYC', N'Seychelles',                                  0, N'SC', N'690'),
(200,N'SLE', N'Sierra Leone',                                0, N'SL', N'694'),
(201,N'SGP', N'Singapore',                                   0, N'SG', N'702'),
(202,N'SXM', N'Sint Maarten (Dutch part)',                   0, N'SX', N'534'),
(203,N'SVK', N'Slovakia',                                    0, N'SK', N'703'),
(204,N'SVN', N'Slovenia',                                    0, N'SI', N'705'),
(205,N'SLB', N'Solomon Islands',                             0, N'SB', N'090'),
(206,N'SOM', N'Somalia',                                     0, N'SO', N'706'),
(207,N'ZAF', N'South Africa',                                0, N'ZA', N'710'),
(208,N'SGS', N'South Georgia and the South Sandwich Islands',0, N'GS', N'239'),
(209,N'SSD', N'South Sudan',                                 0, N'SS', N'728'),
(210,N'ESP', N'Spain',                                       0, N'ES', N'724'),
(211,N'LKA', N'Sri Lanka',                                   0, N'LK', N'144'),
(212,N'SDN', N'Sudan',                                       0, N'SD', N'729'),
(213,N'SUR', N'Suriname',                                    0, N'SR', N'740'),
(214,N'SJM', N'Svalbard and Jan Mayen',                      0, N'SJ', N'744'),
(215,N'SWE', N'Sweden',                                      0, N'SE', N'752'),
(216,N'CHE', N'Switzerland',                                 0, N'CH', N'756'),
(217,N'SYR', N'Syrian Arab Republic',                        0, N'SY', N'760'),
(218,N'TWN', N'Taiwan, Province of China',                   0, N'TW', N'158'),
(219,N'TJK', N'Tajikistan',                                  0, N'TJ', N'762'),
(220,N'TZA', N'Tanzania, United Republic of',                0, N'TZ', N'834'),
(221,N'THA', N'Thailand',                                    0, N'TH', N'764'),
(222,N'TLS', N'Timor-Leste',                                 0, N'TL', N'626'),
(223,N'TGO', N'Togo',                                        0, N'TG', N'768'),
(224,N'TKL', N'Tokelau',                                     0, N'TK', N'772'),
(225,N'TON', N'Tonga',                                       0, N'TO', N'776'),
(226,N'TTO', N'Trinidad and Tobago',                         0, N'TT', N'780'),
(227,N'TUN', N'Tunisia',                                     0, N'TN', N'788'),
(228,N'TUR', N'Turkey',                                      0, N'TR', N'792'),
(229,N'TKM', N'Turkmenistan',                                0, N'TM', N'795'),
(230,N'TCA', N'Turks and Caicos Islands',                    0, N'TC', N'796'),
(231,N'TUV', N'Tuvalu',                                      0, N'TV', N'798'),
(232,N'UGA', N'Uganda',                                      0, N'UG', N'800'),
(233,N'UKR', N'Ukraine',                                     0, N'UA', N'804'),
(234,N'ARE', N'United Arab Emirates',                        0, N'AE', N'784'),
(235,N'GBR', N'United Kingdom',                              0, N'GB', N'826'),
(236,N'USA', N'United States of America',                    0, N'US', N'581'),
(237,N'UMI', N'United States Minor Outlying Islands',        0, N'UM', N'840'),
(238,N'URY', N'Uruguay',                                     0, N'UY', N'858'),
(239,N'UZB', N'Uzbekistan',                                  0, N'UZ', N'860'),
(240,N'VUT', N'Vanuatu',                                     0, N'VU', N'548'),
(241,N'VEN', N'Venezuela (Bolivarian Republic of)',          0, N'VE', N'862'),
(242,N'VNM', N'Viet Nam',                                    0, N'VN', N'704'),
(243,N'VGB', N'Virgin Islands (British)',                    0, N'VG', N'092'),
(244,N'VIR', N'Virgin Islands (U.S.)',                       0, N'VI', N'850'),
(245,N'WLF', N'Wallis and Futuna',                           0, N'WF', N'876'),
(246,N'ESH', N'Western Sahara',                              0, N'EH', N'732'),
(247,N'YEM', N'Yemen',                                       0, N'YE', N'887'),
(248,N'ZMB', N'Zambia',                                      0, N'ZM', N'894'),
(249,N'ZWE', N'Zimbabwe',                                    0, N'ZW', N'716')
) 
src ([CountryId], [CountryCode], [Description], [IsActive], [Alpha2Code], [NumericCode])
ON trgt.CountryId = src.CountryId
WHEN MATCHED THEN
	UPDATE SET 
		[CountryCode]   = src.[CountryCode]
		, [Description] = src.[Description]
		, [Alpha2Code]  = src.[Alpha2Code]
		, [NumericCode] = src.[NumericCode]

WHEN NOT MATCHED THEN
	INSERT (
		[CountryId] 
		,[CountryCode]
		,[Description] 
		,[IsActive]
		,[Alpha2Code]
		,[NumericCode]
	)
	VALUES (
		src.[CountryId] 
		,src.[CountryCode] 
		,src.[Description] 
		,src.[IsActive]
		,src.[Alpha2Code]
		,src.[NumericCode]
	);
-- NOTE: No Deletes Set here